server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server # Eureka实例的主机名
  client:
    register-with-eureka: false # 不把自己注册到服务中心
    fetch-registry: false # 不从Eureka上获取服务注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/ # defaultZone不能使用驼峰、-、_ 等命令方式，否则报错



